#! /bin/bash
for (( i=$1; i<=$2; i++ ))
do
	STR=$(vagrant ssh -c "ls projects/zeek-agent" host$i)
	if [[ "$STR" == *"build"* ]]; then
		echo "host$i was correctly configured"
	else
		echo "host $i was not correctly configured"
	fi
done
