#! /bin/bash
for (( i=$1; i<=$2; i++ ))
do
	STR=$(vagrant ssh -c "screen -ls" host$i)
	while [[ "$STR" == *"Dead"* ]]
	do
		vagrant ssh -c "screen -wipe; screen -d -m -S zeekAgent; screen -S zeekAgent -X stuff 'sudo zeek-agent \n'" host$i
		STR=$(vagrant ssh -c "screen -ls" host$i)
	done
done
