#! /bin/bash
START=$SECONDS
if [ "$2" == "destroy" ]; then
	vagrant destroy -f host$1
elif [ "$2" == "startZeekAgent" ]; then
	vagrant ssh -c "screen -d -m -S zeekAgent; screen -S zeekAgent -X stuff 'sudo zeek-agent \n'" host$1
	STATUS=$(vagrant ssh -c "screen -ls" host$1 | grep -c "Dead")
	while [ $STATUS -eq 1 ]; do
		screen -wipe
		vagrant ssh -c "screen -d -m -S zeekAgent; screen -S zeekAgent -X stuff 'sudo zeek-agent \n'" host$1
		STATUS=$(vagrant ssh -c "screen -ls" host$1 | grep -c "Dead")
	done
elif [ "$2" == "stopZeekAgent" ]; then
	vagrant ssh -c "screen -XS zeekAgent quit" host$1
else
	vagrant $2 host$1
	if [[ "$2" == "up" ]] || [[ "$2" == "reload" ]]
	then
		BUILT="false"
		for (( i=0; i<1000; i++ ))
		do
			STATUS=( $(vagrant status host$1) )
			if [[ "${STATUS[4]}" == "poweroff" ]] || [[ "${STATUS[4]}" == "not" && "${STATUS[5]}" == "created" ]]; then
				vagrant $2 host$1
			elif [ "${STATUS[4]}" == "running" ]; then
				STR=$(vagrant ssh -c "ls projects/zeek-agent" host$1)
				if [[ "$STR" == *"build"* ]]; then
					BUILT="true"
					break
				else
					vagrant $2 host$1
				fi
			fi
		done
		END=$(($SECONDS - $START))
		echo "Time Taken by host$1: "$END" seconds" >> timelogs
		vagrant ssh -c "echo export PATH='$PATH:/home/vagrant/projects/zeek-agent/build' >>~/.bashrc" host$1

	fi
fi
screen -S screen_$1 -X kill
