Vagrant.configure("2") do |config|

  config.vm.define "logger" do |cfg|
    cfg.vm.box = "bento/ubuntu-20.04"
    cfg.vm.hostname = "logger"
    cfg.vm.provision :shell, path: "bootstrap.sh"
    cfg.vm.network :private_network, ip: "192.168.38.105", gateway: "192.168.38.1", dns: "8.8.8.8"

    cfg.vm.provider "vmware_desktop" do |v, override|
      v.vmx["displayname"] = "logger"
      v.memory = 8048
      v.cpus = 4
    end

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.name = "logger"
      vb.customize ["modifyvm", :id, "--memory", 8048]
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end

  end

  (1..24).each do |i|

    config.vm.define "host#{i}" do |cfg|
      cfg.vm.box = "bento/ubuntu-20.04"
      cfg.vm.hostname = "host#{i}"
      cfg.vm.provision :shell, path: "bootstrap-zeek-agent.sh", args: "192.168.38.#{i+50}"
      cfg.vm.network :private_network, ip: "192.168.38.#{i+50}", gateway: "192.168.38.1", dns: "8.8.8.8"
    
      cfg.vm.provider "vmware_desktop" do |v, override|
        v.vmx["displayname"] = "host#{i}"
        v.memory = 2048
        v.cpus = 2
    end
    
      cfg.vm.provider "virtualbox" do |vb, override|
        vb.name = "host#{i}"
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--vram", "32"]
        vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
      end
  end
    
end
end
